### PR TITLE
Improve markdown support to fix #72.

### LINKED ISSUE #72: raml2html-slate-theme doesn't handle markdown in description
Markdown in description is handled as plain text.

Here is a fragment of RAML.

~~~
/users/{id}:
  get:
    queryParameters:
      foo:
        description: |
          blah, blah, blha
          * 1st item
          * 2nd item
        type: string
        required: false
~~~

raml2html-slate-theme generate the following.

screenshot

### PR DESCRIPTION
**Pull request by yyamano**

### CODE REVIEW

**Comment by yyamano** [comment]
Please don't merge this. 
The changes doesn't work with a few RAML files.

**Comment by yyamano** [comment]
Here is an example fragment of RAML.

~~~
/users/{id}:
  get:
    queryParameters: 
      foo:
        description: |
          blah, blah, blah

          this is a longer description.
          * 1st item
          * 2nd item
          ---
          I have no idea why this is processed as an example.
        type: string
        required: false
~~~

Here is a screenshot of generated file.

screenshot-2

Looks  '---' is processed as an example at https://github.com/wdullaer/raml2html-slate-theme/blob/master/index.js#L32

~~~
mdRenderer.hr = () => `</div><div class="set-examples">`
~~~

**Comment by wdullaer** [comment]
Treating hr special for the examples is some legacy piece from an old version of this code.
It's been very long since I worked on this, so I don't remember on top of my head if that is still necessary or not.

Rendering markdown in the descriptions can be useful to set some italic or bold pieces, but if you start using headings or tables you can break the entire layout quite horribly.
I'm not sure yet if giving the users so much rope is a good idea.

What would you use it for?

**Comment by yyamano** [comment]
My colleague developers use heading for appearance adjustment and it work fine with other tool.

I agree with you. Heavy use of markdown in description could make RAML files become over-dependent on a specific tool. I will ask my colleagues to remove headings.

Could you merge the change?

**Comment by wdullaer** [comment]
I'm going to try out the changes on some of my example files here and then merge it.

Should hopefully find some time for that next week.

**Pull request merged**
