### PR TITLE
Expandable examples - Description showed of request body - Types with value any showed without expansion 

### PR DESCRIPTION
**Pull request by estylianou**
Show all avail responses type and examples -- show description of request body/ies if avail

### CODE REVIEW

**Comment by wdullaer** [comment]
Not showing the error response is by design.
Generally speaking your set of errors is generic over most/all endpoints.
You'll get a lot of repetition for every endpoint, without any actual value.

What I used to do was include a static part that covered the errors.

**Comment by estylianou** [comment]
@wdullaer thanks, you are actually right. Could we add the description though on the request body? It seems that if i got many media types is quite confusing to but if i have a description is more readable

e.g
body:
          image/bmp:
            description: Image/bmp
            type: any
          image/x-ms-bmp:
            description: Image/x-ms-bmp
            type: any
          image/gif:
            type: any
          image/jpeg:
            type: any
          image/png:
            type: any
          image/tiff:
            type: any
          application/pdf:
            type: any
          application/msword:
Screenshot from 2020-11-23 15-13-50

**Comment by wdullaer** [comment]
The description on the bodies is a nice addition, I'll happily merge that :-)

Do try to leave your intellij config file out of the commit though (feel free to add that to the .gitignore file).

**Comment by estylianou** [comment]
Cool, thanks :)

**Comment by estylianou** [comment]
@wdullaer let me know if / when we can merge the latest commit :) thank you!

**Comment by estylianou** [comment]
@wdullaer hey, do you have any update on this? :)

**Comment by wdullaer** [comment]
I'm sorry, this fell off the list a bit. I don't have a ton of time these days for my OSS work.
I'll look at it and make a release this weekend.

**Comment by estylianou** [comment]
> I'm sorry, this fell off the list a bit. I don't have a ton of time these days for my OSS work.
> I'll look at it and make a release this weekend.

No problem! thank you for the update :+1:

**Pull request merged**
